// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4e-7S6d55YL3y6-JSsZ8lZsuZSp-DC3M',
    appId: '1:826439841489:web:8d297be22d18388da477f0',
    messagingSenderId: '826439841489',
    projectId: 'grader-a3239',
    authDomain: 'grader-a3239.firebaseapp.com',
    storageBucket: 'grader-a3239.firebasestorage.app',
    measurementId: 'G-MVZMBLYH9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKG6aZI2eq1D8e4wOZM4T9QLlI9JkFdp0',
    appId: '1:826439841489:android:2aca7e44c8ec7c1ba477f0',
    messagingSenderId: '826439841489',
    projectId: 'grader-a3239',
    storageBucket: 'grader-a3239.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6NkNhrzJUPpOnjm7NOKhrPp5igecBRlI',
    appId: '1:826439841489:ios:85fc26ee00eb04b45a47710',
    messagingSenderId: '826439841489',
    projectId: 'grader-a3239',
    storageBucket: 'grader-a3239.firebasestorage.app',
    iosBundleId: 'cloud.grader.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6dNkNhrzOJPpOncjm7NOkfnPp5iqeBRI',
    appId: '1:826439841489:ios:f6bb83412be39dc2a477f0',
    messagingSenderId: '826439841489',
    projectId: 'grader-a3239',
    storageBucket: 'grader-a3239.firebasestorage.app',
    iosBundleId: 'com.graderai.graderAiFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4e-7S6d55YL3y6-JSsZ8lZsuZSp-DC3M',
    appId: '1:826439841489:web:bff9c6bb943eceaaa477f0',
    messagingSenderId: '826439841489',
    projectId: 'grader-a3239',
    authDomain: 'grader-a3239.firebaseapp.com',
    storageBucket: 'grader-a3239.firebasestorage.app',
    measurementId: 'G-8F2RRSPXT1',
  );
}
